DataDog/guarddog

guarddog/analyzer/analyzer.py, guarddog/scanners/package_scanner.py
When scanning one package, I get a mysterious exception from scan_remote(). 
The root cause is the lack of a try catch block for the case of scanning on all source code rules in analyze_sourcecode(), which results in ending execution early if any of the rules throw an exception instead of returning some kind of result. 
During debugging, I also noticed the lack of a rule name in semgrep exceptions, so I added some context when returning errors from the analyze_* functions. 
```
File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "/Users/d.niu/Library/Caches/pypoetry/virtualenvs/guarddog-VURbeFh0-py3.11/lib/python3.11/site-packages/semgrep/c …
```
=> Handle Exceptions For Running All Rules in analyze_sourcecode

pyproject.toml, requirements.txt
I might be a one-off. But not all distributions come with [setuptools](https://pypi.org/project/setuptools/) bundled with Python.
Since the project utilizes [pkg_resources](https://setuptools.pypa.io/en/latest/pkg_resources.html) which is AFAIK a resources from `setuptools` to among other things discover plugins and source files. This needs to be in the requirements/dependency list.
```
Traceback (most recent call last):
File "/usr/sbin/guarddog", line [5](https://github.com/Torxed/archoffline/actions/runs/3541311385/jobs/5945421906#step:9:6), in <module>
from guarddog.cli import cli
File "/usr/lib/python3.10/site-packages/guarddog/cli.py", line 1[7](https://github.com/Torxed/archoffline/actions/runs/3541311385/jobs/5945421906#step:9:8), in <module>
from .scanners.project_scanner import …
```
=> Added setuptools as dependency

.github/workflows/test.yml, Makefile, guarddog/scanners/project_scanner.py, pyproject.toml, tests/core/test_requirements_scanner.py
When scanning requirements.txt files, we shouldn't crash on packages that don't exist on PyPI. See also #78
=> Ignore packages that don't exist in PyPI (closes #78)

docs/Programmatic.md, docs/programmatic-usage.md, guarddog/__init__.py, guarddog/analyzer/analyzer.py, guarddog/cli.py, guarddog/scanners/package_scanner.py, poetry.lock, pyproject.toml
This PR includes a few change needed to make GuardDog run smoothly in aws lambda
Make scan_remote method easy to use programatically:
* move error handling to CLI interface code
* expose the PackageScanner class publicly
* allow override of temporary directory location
* allow keeping the output of the metadata API call
MISC:
* update semgrep
* downgrade lower supported Python version to 3.9
=> Make GuardDog usable as a library rather than only a CLI

guarddog/cli.py
This PR will add exit codes on `scan`.
This will help automating and adding guarddog to runners or scripts, as there's no other way to determine if guarddog found issues or not in a machine friendly way *(other than `grep [1-9]+` or some other shenanigans)*.
This will use `results['issues']` counter, 0 results will exit 0 and anything above will exit with the number of issues.
Assuming a runner similar to https://github.com/Torxed/archoffline/blob/797436de3999e73963af4b60364e0c9767afece9/.github/workflows/guarddog.yaml:
```yaml
on: [ push, pull_request ]
name: guarddog security checkup
jobs:
guarddog:
runs-on: ubuntu-latest
container:
image: archlinux:latest
steps:
- uses: actions/checkout@v3
- run: pacman --noconfirm -Syu git python python-setuptools python-pip python-build
- run: python …
```
=> Adding exit codes

guarddog/scanners/project_scanner.py, tests/core/test_requirements_scanner.py
Make GuardDog ignore lines in requirements that we can't parse and log a proper warning
closes #88
=> Handle requirement file parsing errors

README.md, pyproject.toml
Added some documentation and pinning within `pyproject.toml` (and therefore poetry) to ensure python 3.10
edit: closes #93 93
=> Add python version pin for pyproject.toml and update README

pyproject.toml
Add missing project link to PyPi.
=> pyproject.toml: Add repository url

guarddog/analyzer/sourcecode/code-execution.yml, tests/analyzer/sourcecode/code-execution.py
see #62, this was used in malware and unlikely to be used by legitimate software.
drawback: this rule only scans setup.py so we might want on the long term to create a new rule just for these that scans all files
=> Heuristic: identify usage of globals and __import__ (closes #62)

guarddog/analyzer/metadata/typosquatting.py, requirements.txt, tests/analyzer/metadata/test_typosquatting.py
- If a package has a dot in the name and it is a 'top package', then the typosquatting algorithm reports an error 
- The typosquatting algorithm may report 2 errors for the same package
- Normalize package names according to [PEP 503](https://peps.python.org/pep-0503/) and [PEP 426](https://peps.python.org/pep-0426) using [packaging](https://packaging.pypa.io/en/stable/index.html) -- the same library used by pip
- Typosquatting algorithm now only returns a list of unique 'malicious' packages
- Exit early from the typosquat algorithm if a package is in the 'top packages' list
- Fixed constructor call
- Minor refactoring
- `TestTyposquatting.test_no_duplicate_errors`
- Verify that a package with a typo in the name only reports 1 error
- `TestTyposquatting.test_normalize_names`
- Verify that …
=> Fixing False Positives and Duplicate Errors in the Typosquatting Algorithm

poetry.lock
```
$ osv-scanner --lockfile poetry.lock
╭─────────────┬───────────┬──────────────────┬───────────┬───────────────────────────────────────────────────╮
│ SOURCE      │ ECOSYSTEM │ AFFECTED PACKAGE │ VERSION   │ OSV URL (ID IN BOLD)                              │
├─────────────┼───────────┼──────────────────┼───────────┼───────────────────────────────────────────────────┤
│ poetry.lock │ PyPI      │ certifi          │ 2022.9.24 │ https://osv.dev/vulnerability/GHSA-43fp-rhv2-5gv8 │
╰─────────────┴───────────┴──────────────────┴───────────┴───────────────────────────────────────────────────╯
```
=> chores: Bump certify version to fix GHSA-43fp-rhv2-5gv8

README.md, guarddog/analyzer/sourcecode/silent-process-execution.yml, guarddog/scanners/scanner.py, guarddog/utils/archives.py, tests/analyzer/sourcecode/silent-process-execution.py
=> New rule for "silent execution" of popen based on Pytorch attack. Some cleanup of processing whl files

guarddog/analyzer/sourcecode/__init__.py, guarddog/analyzer/sourcecode/npm-install-script.yml, tests/analyzer/sourcecode/npm-install-script.json
Sample output:
From https://arxiv.org/pdf/2112.10165.pdf:
> We found 2.2% (33,249) of packages use install scripts, indicat- ing that 97.8% of packages may follow npm recommendation of not using the install script as best security practices.
> We found 93.9% (3,412) of malicious packages had atleast one install scripts, indicating that malicious attackers use install scripts frequently.
=> NPM heuristic to identify pre/post-install hooks

guarddog/analyzer/metadata/pypi/empty_information.py, guarddog/analyzer/metadata/pypi/potentially_compromised_email_domain.py, guarddog/analyzer/metadata/pypi/release_zero.py, guarddog/analyzer/metadata/pypi/repository_integrity_mismatch.py, guarddog/analyzer/metadata/pypi/typosquatting.py, guarddog/cli.py, tests/core/test_cli.py
The current implementation considers that the target is local if it exists in the current dir which is incorrect. For instance, `guarddog pypi scan guarddog` would try to scan the **local folder `guarddog`** instead of the remote package, if the folder exists
=> Local target

guarddog/scanners/npm_package_scanner.py, guarddog/scanners/pypi_package_scanner.py, guarddog/scanners/scanner.py, tests/core/test_npm_package_scanner.py
* Before this PR, scanning a namespaced npm package such as `@datadog/browser-logs` caused the package to be extracted to a path containing an `/` which obviously breaks, see #155 
* The code computing the path where the package is extracted was also duplicated
This PR fixes both and adds a simple test
fixes #155
=> Fix package extraction for namespaced npm packages (fixes #155)

guarddog/cli.py, guarddog/scanners/scanner.py, tests/core/test_cli.py
Running `guarddog npm scan .` should scan the local current directory, instead of scanning a remote package called `.`
=> Consider 'guarddog xxx scan .' a local target (fixes #175)

guarddog/analyzer/sourcecode/exec-base64.yml, tests/analyzer/sourcecode/exec-base64.py
[Related issue](https://github.com/DataDog/guarddog/issues/64)
Detect when a Join function is used in an Exec / eval... functions.
This will also catch other types of obfuscation using loop to evade detection
=> Detect when join(...) is used in exec/eval/... functions

guarddog/analyzer/sourcecode/download-executable.yml, tests/analyzer/sourcecode/download-executable.py
Download-executable:
- Detect when the requests library is used (issue #111)
Next step:
- Detecting execution after creating a new file
=> Add new heuristics for the download-executable module

.github/workflows/docker-release.yml, .github/workflows/test.yml, Dockerfile
Last one (for now).
Make the docker builds multi-platform and build linux/amd64 and linux/arm64 at the same time.
Note: Because the base image is Alpine, it has to compile the wheels for both platforms. Compiling for linux/arm64 over virtualization takes significantly longer (~1 minute to ~9 minutes).
=> Build multi-platform images

guarddog/analyzer/metadata/npm/potentially_compromised_email_domain.py, guarddog/analyzer/metadata/pypi/potentially_compromised_email_domain.py, tests/analyzer/metadata/test_potentially_compromised_email_domain.py
In response to this [issue](https://github.com/DataDog/guarddog/issues/258), fixed the sometimes failing PyPI rule `potentially_compromised_email_domain`. 
The rule sometimes fails because the email address stored in `package_info` can be `None` and there is no check that the email_address is `None` before doing any parsing. Added a simple `None` check before returning email addresses for npm and python. Added a test for a None or null email
https://datadoghq.atlassian.net/browse/SINT-1432
=> Fixed Sometimes Failing PyPI potentially_compromised_email_domain

guarddog/analyzer/metadata/pypi/repository_integrity_mismatch.py, tests/analyzer/metadata/test_repository_integrity_mismatch.py
In response to [this](https://github.com/DataDog/guarddog/issues/258), fixed the sometimes failing PyPI rule repository_integrity_mismatch.
The rule sometimes failed because sometime the github URL that was found to be the best url option was not a valid url. To solve this, I added a check to see if the response code of the found best github URL was a 200. I also added a better error message if the repository cloning for pygit2 fails. Added a test as well to check for this failing scenario.
https://datadoghq.atlassian.net/browse/SINT-1432
=> Fixed Sometimes Failing PyPI repository_integrity_mismatch

README.md, guarddog/analyzer/metadata/npm/__init__.py, guarddog/analyzer/metadata/npm/direct_url_dependency.py, guarddog/cli.py, tests/analyzer/metadata/test_direct_url_dependency.py, tests/analyzer/sourcecode/code-execution.py, tests/analyzer/sourcecode/exec-base64.py
This PR adds a new NPM metadata detector, checking for a package dependencies linking to URLs. 
Per NPM's documentation, git, http(s) and Github URLs are indeed supported version strings for a package:
- https://docs.npmjs.com/cli/v10/configuring-npm/package-json#urls-as-dependencies
- https://docs.npmjs.com/cli/v10/configuring-npm/package-json#git-urls-as-dependencies
- https://docs.npmjs.com/cli/v10/configuring-npm/package-json#github-urls
Dependencies fetched this way are not immutable and can be used to inject untrusted code or reduce the likelihood of a reproducible install.
It seems PyPI prevents the upload of Python packages with such links in `install_requires`. It's still possible to set them in `dependency_links` (https://setuptools.pypa.io/en/latest/deprecated/dependency_links.h …
=> [SINT-1536] Add new NPM metadata detector to catch dependencies fetched from URLs

guarddog/cli.py
This should fix the bug reported in https://github.com/DataDog/guarddog/issues/285.
The bug reason was `rule_param` can be `None` if no `rules` or `exclude_rules` are specified by the user. In this case, `list(rule_param)` fails to evaluate (you can't create a list from `None`). Instead the list of all rules for the target ecosystem should be passed to the function.
=> Fix Sarif format regression

guarddog/analyzer/sourcecode/shady-links.yml, tests/analyzer/sourcecode/shady-links.py
The `shady-links` rule try to match suspicious URLs. However, it's not looking for IPs although those are more discrete means to reach C2 instances. This PR add support to detect IPv4 & IPv6
=> Update the shady-links rule to match IPs

guarddog/cli.py
- use sys.exit instead of exit
- Update err message
- Return exit code 1 instead of 0 if exception is caught (Was wondering why my custom CI was passing even though there was an exception)
=> cli: update err msg and exit code

guarddog/analyzer/sourcecode/npm-install-script.yml
Closes https://github.com/DataDog/guarddog/issues/308
=> Stop Reporting NPM Packages with a "prepare" Script

guarddog/scanners/scanner.py
Fixes error found when scanning NPM packages in guarddog-cron: https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fguarddog-cron-dev-guarddog-scan/log-events/2024$252F04$252F02$252F$255B$2524LATEST$255D6c466d58e17c4baba3fc4037e8add1dc
If we scan an NPM package with a slash in its name (ex. `@sroussey/usearch`), Guarddog fails to write the package metadata since it tries to create a file in a dir that doesn't exist. This fixes that bug.
```
LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. However, in rare cases, a Lambda runtime update can cause unexpected function behavior. For functions using managed runtimes, runtime updates can be triggered by a function change, or can …
```
=> [Bugfix] NPM Package Info Writing

guarddog/cli.py
`guarddog  pypi verify --exit-non-zero-on-finding requiremets.txt` always returns 0 code. 
Dictionary format which is passed for verification: 
`[{"dependency": "", "version": "", "result": {"issues": 0, "errors": {}, "results": {}, "path": ""}}]`
`exit_with_status_code` function doesn't expect "issues" to be in the nested dictionary: 
```
for result in results:
num_issues = result.get('issues', 0)
```
=> Pass expected dictionary format for status code verification

README.md, guarddog/analyzer/metadata/npm/npm_metadata_mismatch.py, guarddog/analyzer/sourcecode/npm-obfuscation.yml, tests/analyzer/sourcecode/npm-obfuscation.js
Adds new rule that detects javascript code being purposefully obfuscated.
The goal is to detect the most common patterns used by obfuscates such as:
- Function and parameter renaming 
- String array mapping
- Overcomplicated control flow
=> Add NPM detection of obfuscated javascript code

README.md, guarddog/analyzer/metadata/bundled_binary.py, guarddog/analyzer/metadata/npm/__init__.py, guarddog/analyzer/metadata/npm/bundled_binary.py, guarddog/analyzer/metadata/pypi/__init__.py, guarddog/analyzer/metadata/pypi/bundled_binary.py, tests/analyzer/metadata/test_bundled_binary.py
Adds new rule that detects packages containing EXE or ELF files.
The goal is to detect if executables are smuggled into the system.
This detection makes use of file magic bytes to detect file types regardless of their extension
An false positive analysis scan was performed with the following results: 
- against the top 1k npm produced 4 false positives 
- against the top 1k pypi packages produced 0 false positives
- against the last week pypi ~50 packages with 0 false positives
- against the last week npm ~196 packages with 0 false positives
=> Add detection of compiled binaries in package code 

guarddog/analyzer/sourcecode/npm-obfuscation.yml, tests/analyzer/sourcecode/npm-obfuscation.js
The following is detected as JSFuck
```
console.warn(`
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
WARNING
Version discrepancies between server and "${clientRole}" client:
+ server: ${serverVersion} | client: ${clientVersion}
This might lead to unexpected behavior, you should consider to re-install your
dependencies on both your server and clients.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!`);
}
```
This PR fixes it
=> Adding FP case to npm-obfuscation

Dockerfile
Just a nit, but when using `WORKDIR`  instruction you don't need to create it before. It does it automatically for you. Tested by building new tag and running guarddog commands
=> remove redundant docker layer

guarddog/analyzer/sourcecode/npm-obfuscation.yml, tests/analyzer/sourcecode/npm-obfuscation.js
The following comment triggered the detection by error:
```
/*
button component option
variant = text , contained , outlined
++++++++++++++
text button 
// ok: npm-obfuscation
++++++++++++++
disabled
*/
```
This PR escapes comments in the detection
=> Add exception for wrong JSFuck detection

README.md, guarddog/analyzer/sourcecode/dll-hijacking.yml, guarddog/analyzer/sourcecode/npm-dll-hijacking.yml, tests/analyzer/sourcecode/dll-hijacking.py, tests/analyzer/sourcecode/npm-dll-hijacking.js
Adds new rule that detects when is attempted to load arbitrary DLL or Shared Object to gain execution.
The goal is to detect the most common patterns for DLL hijacking, among:
* DLL side-loading: an object is being fed to a non malicious application
* DLL injection: Append arbitrary code into a running process
* Phantom DLL: Plant a shared object or DLL into the system which is then loaded by a trusted executable
See [here](https://unit42.paloaltonetworks.com/dll-hijacking-techniques) for more information on techniques
A false positive analysis scan was performed with the following results:
- A test was ran against the top 500 npm packages, which produced **0 FP**
- A test was ran against the top 500 pypi packages, which produced **0 FP**
- A test was ran against the most interesting npm …
=> Add DLL hijacking detection

.gitignore, guarddog/analyzer/metadata/npm/typosquatting.py, guarddog/analyzer/metadata/pypi/typosquatting.py, guarddog/scanners/npm_project_scanner.py, guarddog/scanners/pypi_project_scanner.py, guarddog/scanners/scanner.py, guarddog/utils/config.py, tests/core/test_pypi_requirements_scanner.py
closes issue https://github.com/DataDog/guarddog/issues/362
closes issue https://github.com/DataDog/guarddog/issues/262
closes issue https://github.com/DataDog/guarddog/issues/86
**Context**
Guarddog verify command operated against all possible matches of packages. 
So for instance a requirement with `guarddog>=1.0.0`
would result in guarddog verifying all possible matches:
```- 1.0.0
- 1.0.1
- 1.0.2
- ... 
```
This behaviour could lead to a very lengthy scan process and most-likely not the most useful given that only the most recent match is installed by package managers
**Changes**
This PR modifies that behaviour to select by default the best "match" (like a real package manager would do)
So, having the following requirement `guarddog>=1.0.0`
Would result for selecting the latest …
=> Feature: honor requirements versions

guarddog/analyzer/metadata/npm/potentially_compromised_email_domain.py, guarddog/analyzer/metadata/npm/unclaimed_maintainer_email_domain.py, guarddog/analyzer/metadata/potentially_compromised_email_domain.py, guarddog/analyzer/metadata/pypi/potentially_compromised_email_domain.py, guarddog/analyzer/metadata/utils.py
closes https://github.com/DataDog/guarddog/issues/387
The `potentially_compromised_email_domain` rule was producing results when comparing registration dates for some domains such as gmail.com
* potentially_compromised_email_domain: failed to run rule unclaimed_maintainer_email_domain: can't compare offset-naive and offset-aware datetimes
This PR forces to use timezone awareness to all obtained dates in order to compare them
=> Fixing the timezone in dns lookups

guarddog/cli.py
Adds a `--version` flag to the cli for retrival of the GuardDog version.
The actual version detection depends on the packaging. I tried to test this, but it should be reviewed again upon release.
Results are as follows:
* I tested setting the version via `pyproject.toml` by which it is automatically detected:
```bash
❯ poetry run guarddog --version
1.10.0
```
* I briefly made a release check by downloading the current [.tar.gz from pypi](https://pypi.org/project/guarddog/#files) and injected the change from this PR, repackaged, and installed via `pip install guarddog-1.10.0.tar.gz`:
```bash
❯ guarddog
Usage: guarddog [OPTIONS] COMMAND [ARGS]...
GuardDog cli tool to detect malware in package ecosystems
Supports PyPI and npm
Example: guarddog pypi scan semantic-version
Use --help for the …
```
=> add --version flag to cli

README.md, guarddog/analyzer/sourcecode/npm-steganography.yml, tests/analyzer/sourcecode/npm-steganography.js
Adds new rule that detects when package retrieves hidden data from an image and executes it.
This detection was already present for PyPI ecosystem and was introduced for NPM.
A false positive analysis scan was performed with the following results:
A false positive analysis scan was performed with the following results:
- A test was ran against the top 2k npm packages, which produced **0 FP**
- A test was ran against the most interesting npm packages released last week **(~89)**, which produced **0 FP**
=> Add steganography for NPM

guarddog/analyzer/analyzer.py, guarddog/scanners/scanner.py
**Situation:**
The situation occurs when the user excludes a rule using the `-x` switch while scanning a local package.
**Explaination:**
The program attempts to only run sourcecode rules on a folder but the rules are not correctly set. 
**Result:**
The program produces an error while trying to load semgrep rules using metadata rule names.
```
poetry run guarddog npm scan /tmp/sample.tar.gz --output-format=json -x npm-dll-hijacking
{ ...
"errors": {"rules-all": "failed to run rule: \nAn error occurred when running Semgrep....
`...guarddog/analyzer/sourcecode/direct_url_dependency.yml` does not exist\", \"type\": \"SemgrepError\"}
`.../guarddog/analyzer/sourcecode/npm_metadata_mismatch.yml` does not exist\", \"type\": \"SemgrepError\"}
```
=> Bugfix: Input rules are not correctly set in analyzers

guarddog/analyzer/sourcecode/dll-hijacking.yml, guarddog/analyzer/sourcecode/npm-dll-hijacking.yml, guarddog/analyzer/sourcecode/npm-obfuscation.yml
Rules using `<... PATTERN ...>` consume a lot of memory, thus it usage should be avoided.
- `npm-dll-hijacking.yml`: Rule was using `<... PATTERN ...>` 
- `npm-obfuscation`:  Rule was using `<... PATTERN ...>`  and other optimizations and simplifications were introduced
```
output: {"errors": [{"code": 2, "level": "error", "message": "Error while running rules: \n
You are seeing this because the engine was killed.\n\n
The most common reason this happens is because it used too much memory.\n                    If your repo is large (~10k files or more), you have three options:\n                    1. Increase the amount of memory available to semgrep\n                    2. Reduce the number of jobs semgrep runs with via `-j <jobs>`. We\n                        recommend using 1 job if you …
```
=> Improve detection to avoid memory over-usage

guarddog/cli.py, tests/core/test_cli.py
Version v1.11.1 introduced a bug that produced that no rule is assigned to run by default
=> Hotfix: No rules are ran by default 

guarddog/analyzer/sourcecode/dll-hijacking.yml, guarddog/analyzer/sourcecode/npm-dll-hijacking.yml, tests/analyzer/sourcecode/dll-hijacking.py, tests/analyzer/sourcecode/npm-dll-hijacking.js
This PR improves the coverage of the DLL hijacking rules by adding patterns to match strings resembling various Windows commands for executing DLLs.
=> Improve DLL hijacking rule coverage

README.md, guarddog/analyzer/analyzer.py
By the nature of how semgrep works, some of our rules (like obfuscation, shady-links, etc) would find multiple times the same offending line. 
This might lead to report the location and code over and over again.
This PR aims to only append a finding if not already reported.
From this:
```
shady-links: found 951 source code matches
* This package contains an URL to a domain with a suspicious extension at package/lib/index.cjs:1
"use strict";var Kc=Object.create;var vn=Object.defineProperty;var Jc=Object.getOwnPropertyDescriptor;var Qc=Object.getOwnPropertyNames;var Yc=Object.getPrototypeOf,Zc=Object.prototype.hasOwnProperty;var ee=(t,e)=>{for(var r in e)vn(t,r,{ge...}`).join(`
* This package contains an URL to a domain with a suspicious extension at package/lib/index.cjs:1
"use strict";var …
```
=> Remove duplicated sourcode findings

guarddog/cli.py, guarddog/scanners/pypi_package_scanner.py, guarddog/scanners/scanner.py, guarddog/utils/archives.py, tests/core/test_cli.py
This PR makes three principal changes:
1. It simplifies the conditions under which Guarddog will decide to perform a local scan: whenever the target is a directory or a regular file in the local filesystem.  It also eliminates as much as possible duplicate checks related to local targets
2. It adds functions in `guarddog/utils/archives.py` for checking whether a file extension is for a supported archive format and uses them pervasively
3. Closes #411
=> Simplify local target checks

guarddog/analyzer/sourcecode/exfiltrate-sensitive-data.yml, tests/analyzer/sourcecode/exfiltrate-sensitive-data.py
This PR extends the `exfiltrate-sensitive-data` rule with a detection for data exfiltration using `sqlite3`, based on samples observed in the wild.
Closes #232
=> Add detection for Python sqlite3 data exfiltration

README.md, guarddog/cli.py, guarddog/scanners/scanner.py, tests/core/test_cli.py
This PR changes GuardDog's behavior in the case of a local directory scan so that it expects the directory to contain a package.  This makes it so that a local scan always expects a (possibly zipped) package directory as its target.
```shell
$ guarddog pypi scan ~/Downloads/requests-2.32.3.tar.gz
Found 0 potentially malicious indicators scanning ~/Downloads/requests-2.32.3.tar.gz
$ tar -xf ~/Downloads/requests-2.32.3.tar.gz -C ~/Downloads
$ guarddog pypi scan ~/Downloads/requests-2.32.3
Found 0 potentially malicious indicators scanning ~/Downloads/requests-2.32.3
$
```
Closes #425
=> Standardize local scanning behavior

guarddog/cli.py, guarddog/scanners/__init__.py, guarddog/scanners/scanner.py
This PR proposes to eliminate the `Package` class, which superclasses `PackageScanner` and `ProjectScanner`.
Reasons to do this:
1. There is no context in which a `PackageScanner` and a `ProjectScanner` can be used interchangeably without a great deal of difficulty.  These classes have only one common method, `scan_local()`, that expect different kinds (as opposed to types) of arguments: a path to a local package directory or archive for `PackageScanner` versus a path to a `requirements.txt` file for `ProjectScanner`
2. It seems the only purpose of `Package` is to give `scanner.get_scanner()` a definite, non-union return type.  However, we end up paying elsewhere for this simplicity, namely via the explicit cast in `cli._scan()` needed only to satisfy the type checker, so it's not clear …
=> Eliminate Package class

guarddog/analyzer/sourcecode/npm-install-script.yml, tests/analyzer/sourcecode/npm-install-script.json
Removing the following patterns in order to reduce the amount of False Positives of the rule
=> Removing npm-install-script False Positives 

guarddog/utils/archives.py, tests/core/test_cli.py
This PR changes GuardDog so that `bzip2` and `xz` compression are allowed when sourcing a package from a tar archive.  It also permits all common file extensions for these (`.bz2`, `.bzip2`, `.xz`) as well as for `gzip` (`.gz`, `.gzip`), which was already allowed in this context.
For local files, the PR uses the validation functions provided by `tarsafe` and `zipfile` to introspect the file contents (as opposed to just looking at the extension) before attempting to extract.
Closes #427
=> Expand allowed tar archive compression algorithms

guarddog/analyzer/sourcecode/shady-links.yml, tests/analyzer/sourcecode/shady-links.py
Added sites observed in malicious samples 
closes https://github.com/DataDog/guarddog/issues/180
=> Adding new link domains to shady-links

guarddog/analyzer/metadata/bundled_binary.py
This PR updates the `bundled_binary` metadata rule so that it includes `SHA256` hashes of the binary files it finds.
The output format is updated so that files are organized by unique hash.  Each file listed on the same line has the same hash.  These listed files are all distinct, even if they have the same name.
Sample output:
```bash
$ guarddog npm scan sample-package --version 1.1.0 --rules bundled_binary
Found 1 potentially malicious indicators in sample-package
bundled_binary: Binary file/s detected in package:
843b9ff549ab7a1d4a7d60cd224321058029350a88ccb53855969f3a8649a342: conpty.dll (exe), conpty.dll (exe), c.dll (exe)
c081c868cc3c6dc5ca6c950772cd04644c326a18e9727fb188683f214d517409: OpenConsole.exe (exe)
0269664950a8bc65f9d30cb1d64213b3fc50507a3c56c174516d3ae243cbc3e0: …
```
=> Compute SHA-256 in bundled_binary

guarddog/analyzer/sourcecode/exfiltrate-sensitive-data.yml, tests/analyzer/sourcecode/exfiltrate-sensitive-data.py
This PR adds `os.environ` (the mapping object) to the list of sources for the Python `exfiltrate-sensitive-data` rule.
No new false positives were observed in a test against the top 500 Python packages.
=> Enhance exfiltrate-sensitive-data rule

guarddog/analyzer/sourcecode/shady-links.yml
This PR changes the matching on the rule to match on json files and also removal of the slash ending requirement for complete domains regex
No  false positives were observed in a test against the top 1k npm and pypi packages.
=> Enhance shady links rule 

guarddog/analyzer/sourcecode/shady-links.yml
Since domain providers now allow to buy .zip it can be used to bypass checks
=> Added zip domain to shadylinks check

README.md, guarddog/scanners/__init__.py, guarddog/scanners/github_action_project_scanner.py, tests/core/resources/workflow.yaml, tests/core/test_github_action_project_scanner.py
- Add GitHub action support for `verify` command
- Accepts a workflow YAML file
- Parses all 3rd party (non-relative path) actions and their versions
- Performs a scan for each action + version combination
<details>
<summary>Verify action
[`.github/workflow/test.yaml`](https://github.com/DataDog/guarddog/blob/b025d86018a0498d1e888cc372695cf91be9c1da/.github/workflows/test.yml)
</summary>
```
> poetry run guarddog github_action verify .github/workflows/test.yml
INFO: Scanning using at most 16 parallel worker threads
Found 0 potentially malicious indicators scanning actions/setup-python version v5
Found 0 potentially malicious indicators scanning actions/checkout version v4
Found 0 potentially malicious indicators scanning docker/setup-qemu-action version v3
Found 0 potentially malicious …
```
=> [SINT-3008] feat(github-action): add support for 'verify' command 

guarddog/analyzer/metadata/pypi/typosquatting.py, tests/samples/download_legit_pypi_package.sh
To stay within quota, it now has just under 30 days of data, so the filename has been updated. Both will be available for a while. See https://github.com/hugovk/top-pypi-packages/pull/46.
=> Update top-pypi-packages filename

README.md, guarddog/analyzer/sourcecode/go-exec-base64.yml, tests/analyzer/sourcecode/go-exec-base64.go
This PR adds a detection rule to identify Go code that decodes a Base64 string and passes the result to a potentially dangerous execution function. This pattern is commonly used in obfuscated or malicious code to hide payloads from static analysis.
The rule was tested against local test cases as well as the [top 100 Go packages](https://github.com/EvanLi/Github-Ranking/blob/master/Top100/Go.md), with zero potentially malicious indicators matched.
=> Detect Base64-decoded content being passed to execution functions in Go

README.md, guarddog/analyzer/analyzer.py
Timeout is set to 10 seconds
Use of GUARDDOG_SEMGREP_MAX_TARGET_BYTES env variable (default is 10MB) instead of a hard coded constant
Updated README informing users of this configuration change
=> Semgrep timeout fix + use of env variables to set max_target_bytes

README.md, guarddog/analyzer/sourcecode/go-exfiltrate-sensitive-data.yml, tests/analyzer/sourcecode/go-exfiltrate-sensitive-data.go
This PR adds a Semgrep detection rule to identify Go packages that read and exfiltrate sensitive data from the local system.
The rule was tested against a large local code base and the [top 100 Go packages](https://github.com/EvanLi/Github-Ranking/blob/master/Top100/Go.md), with zero potentially malicious indicators matched.
=> [Go - New Detection] Detect data collection and exfiltration in Go

guarddog/analyzer/sourcecode/shady-links.yml
Added files[.]catbox[.]moe to shady links rule as a malware download domain which is marked by 3 VT detection engines as malicious
=> Update shady links rule

guarddog/scanners/pypi_project_scanner.py, tests/core/test_npm_requirements_scanner.py, tests/core/test_pypi_requirements_scanner.py
A requirements file declaring dependencies with no versions would end up not scanning the latest version.
For instance:
```
$ cat /tmp/requirements.txt
disposable-email-domains
```
Would produce:
```
Some rules failed to run while scanning disposable-email-domains:
* download-package: Version  for package disposable-email-domains doesn't exist.%
```
This PR would result in:
```
guarddog --log-level DEBUG pypi verify /tmp/requirements.txt --output-format sarif --exclude-rules repository_integrity_mismatch
DEBUG: Retrieving PyPI package metadata information from https://pypi.org/pypi/disposable-email-domains/json
DEBUG: Retrieved versions 0.0.98, 0.0.124, 0.0.40, 0.0.103, 0.0.93, 0.0.73, 0.0.91, 0.0.68, 0.0.24, 0.0.74, 0.0.38, 0.0.22, 0.0.110, 0.0.94, 0.0.39, 0.0.67, 0.0.102, 0.0.30, …
```
=> Fix scan on empty python dependencies
