guarddog/analyzer/analyzer.py

https://github.com/DataDog/guarddog/pull/68, but against the right target branch

handle exception

---

.github/workflows/test.yml
guarddog/scanners/package_scanner.py
guarddog/utils/archives.py

Bug fix: scanning zip packages

---

.pre-commit-config.yaml
README.md

Add pre-commit hooks configuration for local development

---

guarddog/analyzer/metadata/npm/__init__.py
guarddog/analyzer/metadata/npm/typosquatting.py
guarddog/analyzer/metadata/resources/top_npm_packages.json
guarddog/analyzer/metadata/typosquatting.py
tests/analyzer/metadata/test_typosquatting.py

npm squatting

---

guarddog/analyzer/analyzer.py
tests/core/test_sourcecode_analyzer.py

Don't run Semgrep when no sourcecode rule should be run (fixes #161)

---

README.md
guarddog/analyzer/metadata/pypi/__init__.py
guarddog/analyzer/metadata/pypi/single_python_file.py
tests/analyzer/metadata/test_single_python_file.py

Create new heuristic to identify PyPI packages with a single Python file (closes #160)

---

guarddog/analyzer/sourcecode/exec-base64.yml
tests/analyzer/sourcecode/exec-base64.py

Catch dynamic execution of base64-encoded code through __import__ (fixes #157)

---

guarddog/analyzer/sourcecode/exec-base64.yml
tests/analyzer/sourcecode/exec-base64.py

Catch code execution through exec(...(zlib.decompress(xxx))

---

guarddog/analyzer/analyzer.py

Fix: Only one result per sourcecode rule is shown #187 

---

README.md
guarddog/cli.py

Fix non-working status code option on guarddog verify

---

guarddog/cli.py
guarddog/reporters/sarif.py

isinstance should be used when checking for types

Update type check

---

README.md

update gh action versions in the CI snippet in README

update ci snippet

---

guarddog/scanners/pypi_project_scanner.py

Parameter in docstring didn't match the name of the actual func param

edit docstring param name

---

guarddog/scanners/pypi_package_scanner.py
guarddog/scanners/scanner.py

Simplified some conditional statements for better code readability

refact: Simplify python statements

---

guarddog/analyzer/sourcecode/shady-links.yml
tests/analyzer/sourcecode/shady-links.py

Ignore local IPs often used in tests and exclude testing directories

Address some false positives with shady-links

---

guarddog/analyzer/sourcecode/exfiltrate-sensitive-data.yml
tests/analyzer/sourcecode/cmd-overwrite.py
tests/analyzer/sourcecode/exfiltrate-sensitive-data.py

exfiltrate-sensitive-data: add new ruleid

---

guarddog/analyzer/sourcecode/exec-base64.yml
tests/analyzer/sourcecode/exec-base64.py

Identify when code is decrypted and executed on the fly

---

guarddog/analyzer/sourcecode/download-executable.yml
tests/analyzer/sourcecode/download-executable.py

* Closes https://github.com/DataDog/guarddog/issues/206
* Closes https://github.com/DataDog/guarddog/issues/111 (only added test given that the snippet is already detected)

fix download-executable false negatives

---

guarddog/analyzer/metadata/npm/__init__.py
guarddog/analyzer/metadata/npm/potentially_compromised_email_domain.py
guarddog/analyzer/metadata/npm/unclaimed_maintainer_email_domain.py
guarddog/analyzer/metadata/npm/utils.py
guarddog/analyzer/metadata/potentially_compromised_email_domain.py
guarddog/analyzer/metadata/pypi/__init__.py
guarddog/analyzer/metadata/pypi/potentially_compromised_email_domain.py
guarddog/analyzer/metadata/pypi/unclaimed_maintainer_email_domain.py
guarddog/analyzer/metadata/pypi/utils.py
guarddog/analyzer/metadata/unclaimed_maintainer_email_domain.py
guarddog/analyzer/metadata/utils.py
tests/analyzer/metadata/test_potentially_compromised_email_domain.py
tests/analyzer/metadata/test_unclaimed_maintainer_email_domain.py
tests/analyzer/metadata/utils.py

Closes #333 
* including some necessary code factorization
* plus add warning about false positives for NPM
* including unit tests

Move "unclaimed maintainer email domain" to New Signal

---

README.md
guarddog/analyzer/metadata/unclaimed_maintainer_email_domain.py
guarddog/analyzer/sourcecode/__init__.py
guarddog/analyzer/sourcecode/npm-exfiltrate-sensitive-data.yml
tests/analyzer/sourcecode/npm-exfiltrate-sensitive-data.js

Adds new rule that detects javascript code being purposefully obfuscated.
The goal is to detect the most common patterns used to exfiltrate data such as:
* Usual sensitive files being read
* Usual outbound http 
* Usual exfiltration using other than http libraries

Add NPM detection of sensitive data exfiltration javascript code 

---

guarddog/analyzer/sourcecode/npm-exfiltrate-sensitive-data.yml
tests/analyzer/sourcecode/npm-exfiltrate-sensitive-data.js

closes https://github.com/DataDog/guarddog/issues/123

Add npm-exfiltrate-sensitive-data case

---

guarddog/analyzer/analyzer.py
guarddog/cli.py

closes https://github.com/DataDog/guarddog/issues/353

fix rules assignment per ecosystem

---

guarddog/reporters/sarif.py

introduced by 4ac29f5a919dcb7d2bb3d4f3344bfe94dd2af16b in #365

Bugfix: Fix regression in SARIF reporter

---

guarddog/scanners/scanner.py

Fix typo in environment variable to set scan parallelism

---

guarddog/analyzer/metadata/bundled_binary.py
tests/analyzer/metadata/test_bundled_binary.py

The detection function reseting the detected items by mistake

Bugfix Bundled binary rule

---

guarddog/analyzer/sourcecode/shady-links.yml
tests/analyzer/sourcecode/shady-links.py

Add exceptions to shady-links

---

guarddog/utils/archives.py

We observed that several packages are archived with a file permission set, that results in read error at scan time.
This PR, ensures read and traverse permission are proper for the scan to work

Bugfix: Adding permissions to traverse extracted files and folders

---

guarddog/analyzer/sourcecode/shady-links.yml
tests/analyzer/sourcecode/shady-links.py

Improving patterns in shady links:
* Standardising Allowed chars in the domain 
* Added some interesting domains from https://lots-project.com/ (Live of trusted Sites)
* Excluded some FP

Improve shady-links rule

---

guarddog/analyzer/sourcecode/npm-obfuscation.yml
guarddog/analyzer/sourcecode/obfuscation.yml
tests/analyzer/sourcecode/npm-obfuscation.js
tests/analyzer/sourcecode/obfuscation.py

closes https://github.com/DataDog/guarddog/issues/442

Bugfix: obfuscation False Positive

---

guarddog/analyzer/sourcecode/npm-install-script.yml

Adding a case using npx standard command to patch the package at install time

FP npm-install-script - exclude case

---

guarddog/cli.py
guarddog/scanners/pypi_project_scanner.py
guarddog/scanners/scanner.py

Closes https://github.com/DataDog/guarddog/issues/186
Closes https://github.com/DataDog/guarddog/issues/491

Change logging stream to stderr

---

guarddog/analyzer/sourcecode/npm-exfiltrate-sensitive-data.yml
tests/analyzer/sourcecode/npm-exfiltrate-sensitive-data.js

Adding new case to npm-exfiltration

---

guarddog/analyzer/analyzer.py

Closes https://github.com/DataDog/guarddog/issues/508

Prevent code from bypassing semgrep

---

guarddog/analyzer/sourcecode/code-execution.yml

extending code execution rule to init files
